package com.employee.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Employee")
public class Employee {
	public Employee() {
		
	}
	private String employeeid;
	
	@DynamoDBHashKey(attributeName="employeeid")
	@DynamoDBAutoGeneratedKey
    public String getId() {
		return employeeid;
	}
	public void setId(String employeeid) {
		this.employeeid = employeeid;
	}
	private String firstName;
    @DynamoDBAttribute(attributeName="firstName")
    public String getfirstName() {
    	return firstName;
    }
    public void setfirstName(String firstName) {
    	this.firstName=firstName;
    }
    private String lastName;
    @DynamoDBAttribute(attributeName="lastName")
    public String getlastName() {
    	return lastName;
    }
    public void setlastName(String lastName) {
    	this.lastName=lastName;
    }
    private String email;
    @DynamoDBAttribute(attributeName="email")
    public String getEmail() {
    	return email;
    }
    public void setEmail(String email) {
    	this.email=email;
    }
    private Department department;
    @DynamoDBAttribute(attributeName="department")
    public Department getDepartment() {
    	return department;
    }
    public void setDepartment(Department department) {
    	this.department =department;
    }
    
    public Employee(String employeeid, String firstName, String lastName, String email, Department department) {
		this.employeeid= employeeid;
		this.firstName= firstName;
		this.lastName= lastName;
		this.email= email;
		this.department = department;
	}
    
}